namespace PatrolPal.Enum
{
    public enum DistrictEnum
    {
        Bagalkot = 0,
        Ballari = 1,
        Belagavi = 2,
        BengaluruRural = 3,
        BengaluruUrban = 4,
        Bidar = 5,
        Chamarajanagar = 6,
        Chikballapur = 7,
        Chikkamagaluru = 8,
        Chitradurga = 9,
        DakshinaKannada = 10,
        Davangere = 11,
        Dharwad = 12,
        Gadag = 13,
        Hassan = 14,
        Haveri = 15,
        Kalaburagi = 16,
        Kodagu = 17,
        Kolar = 18,
        Koppal = 19,
        Mandya = 20,
        Mysuru = 21,
        Raichur = 22,
        Ramanagara = 23,
        Shivamogga = 24,
        Tumakuru = 25,
        Udupi = 26,
        UttaraKannada = 27,
        Vijayapura = 28,
        Yadgir = 29,
    }
}
